from chatterbot import ChatBot
from chatterbot.trainers import ListTrainer
import os

bot = ChatBot("Bot") # define bot
trainer = ListTrainer(bot)

# load files available in the local system. Have already downloaded chatterbot-corpus
for files in os.listdir("C:/Users/Owner/Downloads/chatterbot-corpus-master/chatterbot-corpus-master/chatterbot_corpus/data/english/"):
    # open data using the same path
    data = open("C:/Users/Owner/Downloads/chatterbot-corpus-master/chatterbot-corpus-master/chatterbot_corpus/data/english/" + files, "r").readlines()
    # train bot
    trainer.train(data)

# once training is done, get input from user
while True:
    user_input = input("You: ")
    if user_input != "Bye":
        # reply generated by the bot
        reply = bot.get_response(user_input)
        # print the reply
        print("ChatBot: ", reply)
    if user_input.strip() == "Bye":
        print("ChatBot: Bye")
        break








        
    

